### ISSUE TITLE
size mismatch for encoder.embedding.embedding.weight when testing model

### ISSUE THREAD

**Issue by leesunj** [facebookresearch/Permutation-Equivariant-Seq2Seq#1]
Hello,

I was following instructions in the repository (with a very small number of iterations to check that everything is set up properly on my machine) as follows:

python train_equivariant_scan.py --split add_jump --equivariance verb --use_attention --bidirectional --n_iters 500

Output:

<img width="702" alt="Screenshot 2020-04-21 at 22 22 56" src="https://user-images.githubusercontent.com/64106535/79916528-d2e0f700-8420-11ea-9b97-1a9ddd06af7f.png">

I then ran:

python test_equivariant_scan.py --experiment_dir models/add_jump/rnn_GLSTM_hidden_64_directions_2/model1/ --fully_trained

However, the result was a size mismatch error for the encoder embedding weight:

<img width="1661" alt="Screenshot 2020-04-21 at 22 18 15" src="https://user-images.githubusercontent.com/64106535/79915560-13d80c00-841f-11ea-84ef-ed5e42da2635.png">

 Apologies if I have missed something really obvious, but could you please let me know whether I need to run additional steps to solve this issue or this is a bug in the code?

Thank you!

**Comment by Gordonjo** [comment]
Hello, 

Thank you for catching this! There was an issue with the default settings of the train / test scripts, which has now been fixed. If you pull the latest changes, this should now work.
